name: SpawnUtility
main: spawnutility.SpawnUtility
version: 1.0
depend: [CorePlugin]
softdepend: [Multiverse-Core]
commands:
  spawn:
    description: Return to spawn
    usage: /<command>
  setspawn:
    description: Set spawn point
    usage: /<command>
permissions:
  spawnutility.setspawn:
    description: 'Allows the use of /setspawn'
    default: op
